### ISSUE TITLE
Renders attribute with empty value when passed

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay-labs-br/fiber#10]
### Expected behaviour
I think the expected when we pass an empty, `null` or `undefined` value in an expected attribute is that it is not rendered, some cases would use this in favor.

### Example
```javascript
<div>Hello World!</div>
```

### Actual behaviour
```javascript
<div id="">Hello World!</div>
```

**Comment by clovisdasilvaneto** [comment]
It's make sense, let's fix this.
