### ISSUE TITLE
Add logic in setState

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay-labs-br/fiber#2]
### Disclaimer
Add logic to `setState` and cause components to render. We can start with a simple API and then improve. What do you think @clovisdasilvaneto?

### Usage
```javascript
this.setState({
	key: value
});
```

### Location
https://github.com/liferay-labs-br/fiber/blob/206b5245d87c4c94b98a7cf37724d1774897ba58/src/component.js#L37

**Comment by clovisdasilvaneto** [comment]
It's good, let do this
