### ISSUE TITLE
Design architecture

### ISSUE THREAD

**Issue by matuzalemsteles** [liferay-labs-br/fiber#5]
### Disclaimer
We need to design the architecture of the files thinking of server-side rendering and center the Fiber core as isomorphic.

### Suggestion
We can think of a multi-package repository using lerna, but putting all the files in `src` and packages in `packages` with an index giving a `require` to their corresponding files to centralize the share of some libs. Create a folder called `isomorphic` to center the core of the fiber.

### API of component
We can create a `src/isomorphic/FiberBaseClass.js` file as a `Component` API contract to be reused with components outside the browser or as a native app in the future.

**Comment by matuzalemsteles** [comment]
Just putting here, what was said in #5 to continue the speech.

cc @clovisdasilvaneto 

## New names for the files
My proposal is a consistency of names among the files, we currently have:
```
.
+-- isomorphic
|   +-- component.js
|   +-- createComponent.js
|   +-- element.js
+-- renderers
|   +-- render.js
```

My idea is that we use `CamelCase` for filenames and starting with `Fiber`:
```
.
+-- isomorphic
|   +-- FiberComponent.js or FiberBaseClass.js
|   +-- FiberCreateComponent.js
|   +-- FiberElement.js
+-- renderers
|   +-- FiberRender.js
```
What do you think?

**Comment by clovisdasilvaneto** [comment]
That sounds like good, I think is perfect

**Comment by matuzalemsteles** [comment]
Okay, I'm going to send a pr with this change.
